type TerritoryWiseCategoryInterface = {
  ID: number;
  NAME: string;
  DESCRIPTION: string;
  ICON: string;
  subCategories: {
    ID: number;
    NAME: string;
    DESCRIPTION: string;
    IMAGE: string;
    BANNER_IMAGE: string;
  }[];
};
type SubCategoryInterface = {
  ARCHIVE_FLAG?: 'F';
  BANNER_IMAGE: string;
  CATEGORY_ID?: number;
  CATEGORY_NAME?: string;
  CLIENT_ID?: 1;
  CREATED_MODIFIED_DATE?: string;
  DESCRIPTION: string | null;
  ID: number;
  IMAGE: string;
  IS_NEW?: 1 | 0;
  NAME: string;
  READ_ONLY?: 'N';
  SEQ_NO?: number;
  STATUS?: number | 1 | 0;
};
type ServiceInterface = {
  ARCHIVE_FLAG: 'F';
  B2B_PRICE: string | null;
  B2C_PRICE: string | null;
  CATEGORY_ID: number;
  CATEGORY_NAME: string;
  CESS: string;
  CGST: string;
  CLIENT_ID: 1;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  DESCRIPTION: string;
  DETAILS_DESIGNER: string | null;
  DURARTION_HOUR: number;
  DURARTION_MIN: number;
  END_TIME: string;
  EXPRESS_COST: number | string | null;
  ID: number;
  IGST: string;
  IS_EXPRESS: 0 | 1;
  IS_FOR_B2B: 0 | 1;
  IS_JOB_CREATED_DIRECTLY: any | null;
  IS_NEW: 1 | 0;
  IS_PARENT: 0 | 1;
  MAX_QTY: number;
  NAME: string;
  ORG_ID: number;
  PARENT_ID: number;
  PREPARATION_HOURS: number;
  PREPARATION_MINUTES: number;
  QTY: number;
  READ_ONLY: 'N';
  SERVICE_HTML_URL: string;
  SERVICE_IMAGE: string;
  SERVICE_NAME: string | null;
  SERVICE_TYPE: 'O' | 'B';
  SGST: string;
  SHORT_CODE: string;
  START_TIME: string;
  STATUS: 1 | 0;
  SUB_CATEGORY_ID: number;
  SUB_CATEGORY_NAME: string;
  TAX_ID: number;
  TAX_NAME: string;
  TECHNICIAN_COST: number | string;
  UNIT_ID: number;
  VENDOR_COST: string;
  UNIT_NAME: string;
  QUANTITY: number;
  KEY_PRICE: number | string;
  MAPPING_ID: number;
  IS_AVAILABLE: 1 | 0;
  T_SERVICE_TYPE: 'B' | 'O';
  T_PREPARATION_MINUTES: number;
  AVG_RATINGS: number;
  T_PREPARATION_HOURS: number;
  GUARANTEE_ALLOWED: 1 | 0;
  GUARANTEE_PERIOD: number;
  WARRANTY_ALLOWED: 1 | 0;
  WARRANTY_PERIOD: number;
  SERVICE_DETAILS_IMAGE: string;
};
type UserInterface = {
  ACCOUNT_STATUS: 1 | 0;
  ALTCOUNTRY_CODE: string | null;
  ALTERNATE_MOBILE_NO: string | null;
  ARCHIVE_FLAG: 'F';
  CLIENT_ID: 1;
  CLOUD_ID: string | null;
  COMPANY_NAME: string | null;
  COMPANY_ADDRESS: string | null;
  COUNTRY_CODE: string;
  CREATED_MODIFIED_DATE: string;
  CURRENT_ADDRESS_ID: number | null;
  CUSTOMER_CATEGORY_ID: number;
  CUSTOMER_TYPE: 'I' | 'B';
  DEVICE_ID: string | null;
  EMAIL: string;
  GST_NO: string;
  ID: number;
  INDIVIDUAL_COMPANY_NAME: string | null;
  IS_HAVE_GST: any;
  IS_SPECIAL_CATALOGUE: 1 | 0;
  LOGOUT_DATETIME: string | null;
  MOBILE_NO: string;
  NAME: string;
  PAN: string | null;
  PROFILE_PHOTO: string | null;
  READ_ONLY: 'N';
  REGISTRATION_DATE: string;
  SALUTATION: string;
};
type AddressInterface = {
  ADDRESS_LINE_1: string;
  ADDRESS_LINE_2: string;
  ARCHIVE_FLAG?: 'F';
  CITY_ID: number | null;
  CITY_NAME: string | any;
  CLIENT_ID?: 1;
  CONTACT_PERSON_NAME: string | null;
  COUNTRY_ID: number | null;
  COUNTRY_NAME: string | null;
  CREATED_MODIFIED_DATE?: string;
  CUSTOMER_ID: number;
  CUSTOMER_NAME: string;
  DISTRICT_ID: number;
  DISTRICT_NAME: string;
  EMAIL_ID: string | null;
  GEO_LOCATION: string;
  ID: number;
  IS_DEFAULT: 1 | 0;
  MOBILE_NO: string;
  PINCODE: string;
  PINCODE_ID: any;
  PINCODE_FOR: string;
  READ_ONLY?: 'N';
  STATE_ID: number;
  STATE_NAME: string;
  TERRITORY_ID: number | null;
  TERRITORY_NAME: string;
  TYPE: string;
  LANDMARK: string;
};
type TerritoryInterface = {
  ARCHIVE_FLAG: 'F';
  BRANCH_ID: number | null;
  BRANCH_NAME: number | null;
  CLIENT_ID: 1;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_MODIFIED_DATE: string;
  END_TIME: string;
  ID: number;
  IS_ACTIVE: 1 | 0;
  IS_EXPRESS_SERVICE_AVAILABLE: 1 | 0;
  NAME: string;
  READ_ONLY: 'N';
  SEQ_NO: number;
  START_TIME: string;
  STATUS: 1 | 0;
  SUPPORT_CONTACT_NUMBER: string;
  SUPPORT_COUNTRY_CODE: string;
};
type PinCode = {
  ARCHIVE_FLAG: string;
  CIRCLE_NAME: string;
  CLIENT_ID: number;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_MODIFIED_DATE: string;
  DISTRICT: number;
  DISTRICT_NAME: string;
  DIVISION_NAME: string;
  HEAD_OFFICE: string;
  ID: number;
  _id: string;
  IS_ACTIVE: number;
  LATTITUDE: string;
  LONGITUDE: string;
  OFFICE_NAME: string;
  PINCODE: string;
  PINCODE_NUMBER: string;
  READ_ONLY: string;
  SEQ_NO: number;
  STATE: number;
  STATE_NAME: string;
  SUB_OFFICE: string;
  TALUKA: string;
  PINCODE_FOR: string;
};
type TerritoryPinCodeMapping = {
  ARCHIVE_FLAG: 'F';
  CIRCLE_NAME: string;
  CLIENT_ID: 1;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_MODIFIED_DATE: string;
  DISTRICT: number;
  DISTRICT_NAME: string;
  DIVISION_NAME: string;
  END_TIME: string;
  ID: number;
  IS_ACTIVE: string;
  IS_EXPRESS_SERVICE_AVAILABLE: 0 | 1;
  OFFICE_NAME: string;
  PINCODE: string;
  PINCODE_ID: number;
  READ_ONLY: 'N';
  START_TIME: string;
  STATE: number;
  STATE_NAME: string;
  STATUS: 'M';
  TALUKA: string;
  TERRITORY_ID: number;
  TERRITORY_NAME: string;
};
type Country = {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  ID: number;
  IS_ACTIVE: number;
  NAME: string;
  READ_ONLY: string;
  SEQ_NO: number;
  SHORT_CODE: string;
};
type State = {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_MODIFIED_DATE: string;
  ID: number;
  IS_ACTIVE: number;
  NAME: string;
  READ_ONLY: string;
  SEQ_NO: number;
  SHORT_CODE: string;
};
type District = {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_MODIFIED_DATE: string;
  ID: number;
  IS_ACTIVE: number;
  NAME: string;
  READ_ONLY: string;
  REMARK: string | null;
  REFUND_STATUS: string | null;
  SERVICE_ADDRESS: string;
  SERVICE_ADDRESS_ID: number;
  SERVICE_COUNT: number;
  SERVICE_LATITUDE: string;
  SERVICE_LONGITUDE: string;
  SPECIAL_INSTRUCTIONS: string;
  STATE_ID: number;
  STATE_NAME: string;
};
type City = {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_MODIFIED_DATE: string;
  DISTRICT_ID: number;
  DISTRICT_NAME: string;
  ID: number;
  IGST: string;
  IS_EXPRESS: number;
  IS_JOB_CREATED_DIRECTLY: number;
  JOB_CARD_ID: number;
  JOB_CARD_NO: string;
  JOB_STATUS: string;
  JOB_CART_STATUS: string;
  MAX_QTY: number;
  MOBILE_NO: string | null;
  ORDER_CATEGORY_NAME: string;
  ORDER_ID: number;
  ORDER_NUMBER: string;
  ORDER_SERVICE_NAME: string;
  ORDER_SERVICE_PARENT_NAME: string | null;
  ORDER_STATUS: string;
  ORDER_SUB_CATEGORY_NAME: string;
  PREPARATION_HOURS: number;
  PREPARATION_MINUTES: number;
  QUANTITY: number;
  RATE: string;
  READ_ONLY: string;
  REFUND_STATUS: string;
  SCHEDULED_DATE_TIME: string | null;
  SERVICE_ADDRESS_ID: number;
  SERVICE_CATALOGUE_ID: number;
  SERVICE_ITEM_ID: number;
  SERVICE_NAME: string;
  SERVICE_PARENT_NAME: string | null;
  SGST: string;
  SPECIAL_INSTRUCTIONS: string;
  START_TIME: string;
  SUB_CATEGORY_ID: number;
  SUB_CATEGORY_NAME: string;
  TAX_AMOUNT: string;
  TAX_EXCLUSIVE_AMOUNT: string | any;
  TAX_INCLUSIVE_AMOUNT: string;
  TAX_RATE: string;
  TECHNICIAN_COST: string;
  TECHNICIAN_ID: number | null;
  TECHNICIAN_NAME: string | null;
  TERRITORY_ID: number;
  TOTAL_AMOUNT: string;
  TOTAL_DURATION_MIN: number;
  TOTAL_TAX_EXCLUSIVE_AMOUNT: any;
  UNIT_ID: number;
  UNIT_NAME: string;
  VENDOR_COST: string;
  VENDOR_ID: number | null;
};
interface cartInterface {
  ARCHIVE_FLAG?: 'F';
  INVENTORY_ID: number;
  SELLING_PRICE: number;
  INVENTORY_IMAGE: string;
  CURRENT_STOCK: number;
  VARIANT_COMBINATION: string;
  DESCRIPTION: string;
  IS_HAVE_VARIANTS: number;
  DISCOUNTED_PRICE: number;
  DISCOUNT_ALLOWED: number;
  SERVICE_RATING: number;
  CART_ID: number;
  CATEGORY_ID: number;
  CATEGORY_NAME: string;
  CESS?: string;
  CGST?: string;
  IGST?: string;
  SGST?: string;
  CLIENT_ID?: 1;
  CREATED_MODIFIED_DATE?: string;
  DURARTION_HOUR: number;
  DURARTION_MIN: number;
  END_TIME: string;
  EXPRESS_CHARGES?: string;
  ID: number;
  IS_DELETED?: 0 | 1;
  IS_EXPRESS: 0 | 1;
  IS_JOB_CREATED_DIRECTLY?: null | 0 | 1;
  MAX_QTY: number;
  PREPARATION_HOURS?: number;
  PREPARATION_MINUTES?: number;
  QUANTITY: number;
  READ_ONLY?: 'N';
  SERVICE_CATALOGUE_ID?: number;
  SERVICE_ID: number;
  SERVICE_NAME: string;
  SERVICE_IMAGE: string;
  SERVICE_PARENT_NAME?: string;
  START_TIME: string;
  SUB_CATEGORY_ID: number;
  SUB_CATEGORY_NAME: string;
  TAX_AMOUNT?: string;
  TAX_EXCLUSIVE_AMOUNT?: string;
  TAX_RATE?: string;
  TOTAL_DURARTION_MIN: string;
  TOTAL_PRICE?: string;
  UNIT_NAME: string;
  UNIT_PRICE?: string;
  QUANTITY_PER_UNIT: number;
  UNIT_ID: number;
}
interface cartInfoInterface {
  ADDRESS_ID: string;
  ADDRESS_LINE_1: string;
  ADDRESS_LINE_2: string;
  ARCHIVE_FLAG: 'F';
  BUILDING: string | null;
  CITY_ID: number | null;
  CITY_NAME: string | null;
  CLIENT_ID: number;
  CONTACT_PERSON_NAME: string;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  COUPON_AMOUNT: string;
  COUPON_CODE: string;
  CREATED_DATE: string;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  DISCOUNT_AMOUNT: string;
  DISTRICT_ID: number;
  DISTRICT_NAME: string;
  EMAIL_ID: string;
  EXPRESS_CHARGES: string;
  FINAL_AMOUNT: string;
  FLOOR: string | null;
  HOUSE_NO: string | null;
  ID: number;
  IS_EXPRESS: 0 | 1;
  IS_ORDER_GENERATED: number | null;
  EXPECTED_DELIVERY_CHARGES: string;
  IS_SAME_STATE: 0 | 1;
  IS_TEMP_CART: number | null;
  LANDMARK: string | null;
  MOBILE_NO: string;
  PAYMENT_MODE: string | null;
  PAYMENT_STATUS: string | null;
  PINCODE: string;
  PINCODE_ID: string;
  READ_ONLY: 'N';
  REMARK: string;
  SCHEDULE_DATE: string;
  SCHEDULE_END_TIME: string;
  SCHEDULE_START_TIME: string;
  SERVICE_COUNT: number;
  STATE_ID: number;
  STATE_NAME: string;
  STATUS: string;
  TAX_AMOUNT: string;
  TERRITORY_ID: number;
  TOTAL_AMOUNT: string;
  TOTAL_QUANTITY: number;
  TOTAL_TAXABLE_AMOUNT: string;
  TYPE: string;
}
interface CancelReason {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  ID: number;
  IS_ACTIVE: number;
  READ_ONLY: string;
  REASON: string;
}
interface orderJobStatus {
  ACTION_DETAILS: string;
  ACTION_LOG_TYPE: string;
  ACTUAL_DISPATCH_DATETIME: string | null;
  ACTUAL_PREAPARATION_DATETIME: string | null;
  CLIENT_ID: number;
  CUSTOMER_ID: number;
  DATE_TIME: string;
  EXPECTED_DATE_TIME: string | null;
  EXPECTED_DISPATCH_DATETIME: string | null;
  EXPECTED_PACKAGING_DATETIME: string | null;
  EXPECTED_PREAPARATION_DATETIME: string | null;
  LOG_TYPE: string;
  ORDER_DATE_TIME: string | null;
  ORDER_ID: number;
  ORDER_MEDIUM: string;
  ORDER_NUMBER: string;
  ORDER_STATUS: string;
  PAYMENT_MODE: string;
  PAYMENT_STATUS: string;
  TOTAL_AMOUNT: number;
  USER_ID: number;
  USER_NAME: string;
  __v: number;
  _id: string;
  createdAt: string;
  updatedAt: string;
}
interface partListDetail {
  ACTUAL_UNIT_ID: number;
  ACTUAL_UNIT_NAME: string;
  ARCHIVE_FLAG: string;
  BATCH_NO: string | null;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  ID: number;
  INVENTORY_CATEGORY_NAME: string;
  INVENTORY_ID: number;
  INVENTORY_NAME: string;
  INVENTRY_SUB_CATEGORY_NAME: string;
  ITEM_ID: number;
  ITEM_NAME: string;
  JOB_CARD_ID: number;
  JOB_CARD_NO: string;
  ORDER_ID: number;
  ORDER_NO: string;
  PAYMENT_STATUS: string;
  QUANTITY: number;
  RATE: string;
  READ_ONLY: string;
  REMARK: string;
  REQUESTED_DATE_TIME: string;
  REQUEST_MASTER_ID: number;
  SERIAL_NO: string | null;
  STATUS: string;
  TAX_RATE: string;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string;
  TOTAL_AMOUNT: string;
  WAREHOUSE_ID: number;
}

// type orderList = any;
// type orderDetails = any;

interface orderList {
  JOB_CARD_ID: any;
  SERVICE_IMAGE: any;
  ORDER_ID: any;
  WARRANTY_ALLOWED: any;
  WARRANTY_PERIOD: any;
  GUARANTEE_ALLOWED: any;
  GUARANTEE_PERIOD: any;
  ACCEPTANCE_REMARK: string | null;
  ADDRESS_LINE_1: string;
  ADDRESS_LINE_2: string;
  ARCHIVE_FLAG: 'T' | 'F';
  BILLING_ADDRESS_ID: number;
  BILLING_ADDRESS_LINE_1: string;
  BILLING_ADDRESS_LINE_2: string;
  BILLING_CITY_NAME: string | null;
  BILLING_COUNTRY_NAME: string;
  BILLING_PINCODE: string;
  BILLING_STATE_NAME: string;
  CANCELLATION_REMARK: string | null;
  CANCEL_DATE: string | null;
  CART_ID: number | null;
  CITY_NAME: string | null;
  CLIENT_ID: number;
  COMPANY_NAME: string | null;
  COUNTRY_NAME: string;
  COUPON_AMOUNT: string | null;
  COUPON_CODE: string | null;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  CUSTOMER_NAME: string;
  CUSTOMER_TYPE: string;
  DISCOUNT_AMOUNT: string;
  EMAIL: string;
  EXPECTED_DATE_TIME: string;
  EXPRESS_DELIVERY_CHARGES: string;
  FINAL_AMOUNT: string;
  ID: number;
  IGST_TAX_AMOUNT: string | null;
  IS_EXPRESS: number;
  IS_SAME_STATE: number;
  MOBILE_NO: string;
  OEDER_COMPLETED_DATETIME: string | null;
  ORDER_ACCEPTED_DATE: string | null;
  ORDER_CREATED_BY: string | null;
  ORDER_CREATER_ID: number | null;
  ORDER_DATE_TIME: string;
  ORDER_MEDIUM: string;
  ORDER_NUMBER: string;
  ORDER_REJECTED_DATE: string | null;
  ORDER_STATUS: string;
  ORDER_STATUS_ID: number;
  ORDER_STATUS_NAME: string;
  PAYMENT_MODE: string;
  PAYMENT_STATUS: string;
  PINCODE: string;
  READ_ONLY: 'Y' | 'N';
  REFUND_STATUS: string | null;
  REMARK: string | null;
  RESCHEDULE_APPROVE_DATE: string | null;
  RESCHEDULE_REQUEST_DATE: string | null;
  RESCHEDULE_REQUEST_REASON: string | null;
  RESCHEDULE_REQUEST_REMARK: string | null;
  SERVICE_ADDRESS: string;
  SERVICE_ADDRESS_ID: number;
  SERVICE_COUNT: number;
  SERVICE_LATITUDE: string;
  SERVICE_LONGITUDE: string;
  SPECIAL_INSTRUCTIONS: string;
  STATE_ID: number;
  STATE_NAME: string;
  TAX_AMOUNT: string;
  TAX_RATE: string;
  TERRITORY_ID: number;
  TERRITORY_NAME: string;
  TOTAL_AMOUNT: string;
  TOTAL_TAX: string | null;
  TOTAL_TAXABLE_AMOUNT: string;
  IS_CANCELATION_REQUESTED: number;
  REJECTION_REMARK: string | null;
  MANUAL_COURIER_URL: any;

  IS_SHIP_ORDER: any;
}
interface orderDetails {
  LATITUDE: string;
  LONGITUDE: string;
  ADDRESS_LINE_1: string;
  ADDRESS_LINE_2: string;
  ARCHIVE_FLAG: string;
  BILLING_ADDRESS_ID: number;
  CATEGORY_ID: number;
  CATEGORY_NAME: string;
  CESS: string;
  CGST: string;
  CLIENT_ID: number;
  CONTACT_PERSON_NAME: string | null;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_BILLING_ADDRESS_ID: number;
  CUSTOMER_ID: number;
  CUSTOMER_SERVICE_ADDRESS_ID: number;
  DURATION_HOUR: number;
  DURATION_MIN: number;
  END_TIME: string;
  ESTIMATED_TIME_IN_MIN: number;
  EXECUTION_DATE_TIME: string | null;
  EXPECTED_DATE_TIME: string;
  EXPRESS_DELIVERY_CHARGES: string;
  ID: number;
  IGST: string;
  IS_EXPRESS: number;
  IS_JOB_CREATED_DIRECTLY: number;
  JOB_CARD_ID: number;
  JOB_CARD_NO: string;
  JOB_STATUS: string;
  JOB_START_TIME: string;
  JOB_END_TIME: string;
  JOB_CART_STATUS: string;
  MAX_QTY: number;
  MOBILE_NO: string | null;
  ORDER_CATEGORY_NAME: string;
  ORDER_ID: number;
  ORDER_NUMBER: string;
  ORDER_SERVICE_NAME: string;
  ORDER_SERVICE_PARENT_NAME: string | null;
  ORDER_STATUS: string;
  ORDER_SUB_CATEGORY_NAME: string;
  PREPARATION_HOURS: number;
  PREPARATION_MINUTES: number;
  QUANTITY: number;
  RATE: string;
  READ_ONLY: string;
  REFUND_STATUS: string;
  SCHEDULED_DATE_TIME: string | null;
  SERVICE_ADDRESS_ID: number;
  SERVICE_CATALOGUE_ID: number;
  SERVICE_ITEM_ID: number;
  SERVICE_NAME: string;
  SERVICE_PARENT_NAME: string | null;
  SGST: string;
  SPECIAL_INSTRUCTIONS: string;
  START_TIME: string;
  SUB_CATEGORY_ID: number;
  SUB_CATEGORY_NAME: string;
  TAX_AMOUNT: string;
  TAX_EXCLUSIVE_AMOUNT: string | any;
  TAX_INCLUSIVE_AMOUNT: string;
  TECHNICIAN_MOBILE_NUMBER: any;
  TAX_RATE: string;
  TECHNICIAN_COST: string;
  TECHNICIAN_ID: number | null;
  TECHNICIAN_NAME: string | null;
  TERRITORY_ID: number;
  TOTAL_AMOUNT: string;
  TOTAL_DURATION_MIN: number;
  TOTAL_TAX_EXCLUSIVE_AMOUNT: any;
  UNIT_ID: number;
  UNIT_NAME: string;
  VENDOR_COST: string;
  VENDOR_ID: number | null;
  GUARANTEE_ALLOWED?: 1 | 0;
  GUARANTEE_PERIOD?: number;
  WARRANTY_ALLOWED?: 1 | 0;
  WARRANTY_PERIOD?: number;
  SERVICE_IMAGE: any;
}

type cartSummeryInterface = {
  ADDRESS_ID: string;
  ADDRESS_LINE_1: string;
  ADDRESS_LINE_2: string;
  ADDRESS_TYPE: string;
  ARCHIVE_FLAG: string;
  BUILDING: string | null;
  CITY_ID: string | null;
  CITY_NAME: string | null;
  CLIENT_ID: number;
  CONTACT_PERSON_NAME: string;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  COUPON_AMOUNT: string;
  COUPON_CODE: string | null;
  COUPON_ID: string | null;
  CREATED_DATE: string;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  DISCOUNT_AMOUNT: string;
  DISTRICT_ID: number;
  DISTRICT_NAME: string;
  EMAIL_ID: string;
  EXPECTED_DATE_TIME: string | null;
  EXPRESS_CHARGES: string | null;
  FINAL_AMOUNT: string;
  FLOOR: string | null;
  HOUSE_NO: string | null;
  ID: number;
  IS_EXPRESS: number;
  IS_ORDER_GENERATED: null;
  IS_SAME_STATE: 1;
  IS_TEMP_CART: null;
  LANDMARK: string | null;
  MOBILE_NO: string;
  PAYMENT_MODE: string | null;
  PAYMENT_STATUS: string | null;
  PINCODE: string;
  PINCODE_ID: string;
  READ_ONLY: string;
  REMARK: string | null;
  SCHEDULE_DATE: string | null;
  SCHEDULE_END_TIME: string | null;
  SCHEDULE_START_TIME: string | null;
  SERVICE_COUNT: number;
  STATE_ID: number;
  STATE_NAME: string;
  STATUS: string;
  TAX_AMOUNT: string;
  TERRITORY_ID: number;
  TOTAL_AMOUNT: string;
  TOTAL_QUANTITY: number;
  TOTAL_TAXABLE_AMOUNT: string;
  TYPE: string;
  EXPECTED_DELIVERY_CHARGES: string;
};

type ServicesInterface = {
  IS_PARENT: number;
  QTY: number;
  TOTAL_PRICE: number;
  PRICE: number;
  QUANTITY: number;
  SERVICE_IMAGE?: string;
  PREPARATION_HOURS: number;
  PREPARATION_MINUTE: number;
  DURARTION_HOUR: number;
  DURARTION_MIN: number;
  SERVICE_NAME: string;
  SERVICE_RATING: number;
  SERVICE_DESCRIPTION?: string;
  SERVICE_START_TIME: string;
  SERVICE_END_TIME: string;
  SERVICE_ID: number;
  CART_ID: number;
  CART_ITEM_ID: number;
  EXPRESS_CHARGES?: string;
  CESS?: string;
  CGST?: string;
  IGST?: string;
  SGST?: string;
  IS_EXPRESS: 0 | 1 | number;
  MAX_QTY?: number;
  CATEGORY_ID: number;
  CATEGORY_NAME: string;
  SUB_CATEGORY_ID: number;
  SUB_CATEGORY_NAME: string;
  SERVICE_PARENT_ID?: number | null;
  SERVICE_PARENT_NAME?: string | null;
  TAX_AMOUNT?: string;
  TAX_RATE?: string;
  GUARANTEE_ALLOWED?: 1 | 0;
  GUARANTEE_PERIOD?: number;
  WARRANTY_ALLOWED?: 1 | 0;
  WARRANTY_PERIOD?: number;
  SERVICE_DETAILS_IMAGE?: string;
};
interface topServiceInterface {
  ARCHIVE_FLAG: string;
  AVG_RATINGS: string;
  B2B_PRICE: string;
  B2C_PRICE: string;
  CATEGORY_ID: number;
  CATEGORY_NAME: string;
  CESS: string;
  CGST: string;
  CLIENT_ID: number;
  CREATED_DATE: string;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  DESCRIPTION: string;
  DETAILS_DESIGNER: string | null;
  DURARTION_HOUR: number;
  DURARTION_MIN: number;
  END_TIME: string;
  EXPRESS_COST: string | null;
  HSN_CODE: string | null;
  HSN_CODE_ID: string | null;
  ID: number;
  IGST: string;
  IS_EXPRESS: number;
  IS_FOR_B2B: number;
  IS_JOB_CREATED_DIRECTLY: number;
  IS_NEW: number;
  IS_PARENT: number;
  MAX_QTY: string;
  NAME: string;
  ORG_ID: number;
  PARENT_ID: number;
  PREPARATION_HOURS: number;
  PREPARATION_MINUTES: number;
  QTY: string;
  READ_ONLY: string;
  SERVICE_HTML_URL: string;
  SERVICE_IMAGE: string;
  SERVICE_NAME: string | null;
  SERVICE_TYPE: string;
  SGST: string;
  SHORT_CODE: string;
  START_TIME: string;
  STATUS: number;
  SUB_CATEGORY_ID: number;
  SUB_CATEGORY_NAME: string;
  TAX_ID: number;
  TAX_NAME: string;
  TECHNICIAN_COST: number;
  UNIT_ID: number;
  UNIT_NAME: string;
  VENDOR_COST: string;
}

interface CartProduct {
  PRODUCT_NAME: string;
  CART_ID: number;
  CART_ITEM_ID: number;
  ID: number;
  DISCOUNTED_PRICE: number;
  SELLING_PRICE: number;
  INVENTORY_IMAGE: string;
  CURRENT_STOCK: number;
  ITEM_NAME: string;
  VARIANT_COMBINATION: string;
  QUANTITY: number;
  IS_HAVE_VARIANTS: number;
  DESCRIPTION: string;
  DISCOUNT_ALLOWED: number;
  QUANTITY_PER_UNIT: number;
  UNIT_ID: number;
  UNIT_NAME: string;
}

interface PaymentRecord {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  ID: number;
  JOB_CARD_ID: number;
  PAYMENT_STATUS: string;
  READ_ONLY: string;
  REMARK: string | null;
  REQUESTED_DATE_TIME: string;
  STATUS: string;
  TECHNICIAN_ID: number;
  TOTAL_AMOUNT: any;
  TOTAL_RATE: string;
  TOTAL_TAX_RATE: string;
}
interface FAQ {
  ANSWER: string;
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  FAQ_HEAD_ID: number;
  FAQ_HEAD_NAME: string;
  FAQ_HEAD_STATUS: number;
  FAQ_ORGANISATION_NAME: string;
  ID: number;
  NEGATIVE_COUNT: number;
  NEGATIVE_FLAG: number;
  ORG_ID: number;
  POSITIVE_COUNT: number;
  QUESTION: string;
  READ_ONLY: string;
  SEQ_NO: number;
  STATUS: number;
  TAGS: string;
  URL: string;
}
interface JobNotification {
  ARCHIVE_FLAG: string;
  ATTACHMENT: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  DESCRIPTION: string;
  ID: number;
  IS_ACTIVE: any; // Can be null or boolean based on your system
  JOB_CARD_NO: string | null;
  MEMBER_ID: number;
  NOTIFICATION_TYPE: string;
  ORDER_ID: string | null;
  ORDER_NO: string | null;
  OWNER_ID: number;
  READ_ONLY: string;
  SEQ_NO: number | null;
  SERVICE_FULL_NAME: string | null;
  SERVICE_NAME: string | null;
  STATUS: string;
  TITLE: string;
  TYPE: string;
}

interface Product {
  ALERT_STOCK_LEVEL: number;
  ARCHIVE_FLAG: string;
  AVG_LEVEL: number;
  BASE_PRICE: string;
  BASE_QUANTITY: number;
  BASE_UNIT_ID: number;
  BASE_UNIT_NAME: string;
  BRAND_ID: number;
  BRAND_NAME: string;
  BREADTH: null;
  CESS: string;
  CGST: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CURRENT_STOCK: string;
  CURRENT_STOCK_NEW: number;
  DATE_OF_ENTRY: string;
  DESCRIPTION: string;
  DISCOUNTED_PERCENTAGE: null;
  DISCOUNTED_PRICE: number;
  DISCOUNT_ALLOWED: number;
  EXPECTED_DELIVERY_CHARGES: string;
  EXPECTED_DELIVERY_IN_DAYS: number;
  EXPIRY_DATE_ALLOWED: number;
  GUARANTEE_ALLOWED: number;
  GUARANTEE_PERIOD: number;
  HEIGHT: null;
  HSN_ID: number;
  HSN_NAME: string;
  ID: number;
  IGST: string;
  INVENTORY_CATEGORY_ID: number;
  INVENTORY_CATEGORY_NAME: string;
  INVENTORY_IMAGE: string;
  INVENTORY_TRACKING_TYPE: string;
  INVENTORY_TYPE: string;
  INVENTRY_SUB_CATEGORY_ID: number;
  INVENTRY_SUB_CATEGORY_NAME: string;
  IS_ALREADY_IN_CART: number;
  IS_HAVE_VARIANTS: number;
  IS_NEW: number;
  IS_SET: number;
  IS_VERIENT: number;
  ITEM_NAME: string;
  LENGTH: null;
  NAME: string;
  PARENT_ID: number;
  PARENT_ITEM_NAME: null;
  QUANTITY_PER_UNIT: number;
  RATING: null;
  READ_ONLY: string;
  REORDER_STOCK_LEVEL: number;
  REPLACEMENT_ALLOW: number;
  REPLACEMENT_PERIOD: number;
  RETURN_ALLOW_PERIOD: number;
  RETURN_ALOW: number;
  SELLING_PRICE: number;
  SGST: string;
  SHORT_CODE: string;
  SKU_CODE: string;
  STATUS: number;
  TAX_ID: number;
  TAX_NAME: string;
  TAX_PREFERENCE: string;
  UNIT_ID: number;
  UNIT_NAME: string;
  UNIT_STOCK: number;
  VARIANT_COMBINATION: null;
  VARIANT_NAME: string;
  WAREHOUSE_NAME: null;
  WARRANTY_ALLOWED: number;
  WARRANTY_CARD: string;
  WARRANTY_PERIOD: number;
  WEIGHT: null;
  INVENTORY_DETAILS_IMAGE: string;
}

interface InvoiceInterface {
  ARCHIVE_FLAG: string;
  BILLING_ADDRESS_ID: number;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  CUSTOMER_NAME: string;
  CUSTOMER_TYPE: string;
  DISCOUNT_AMOUNT: string;
  EMAIL: string;
  FINAL_AMOUNT: string;
  ID: number;
  INVOICE_DATE: string;
  INVOICE_URL: string;
  JOB_CARD_ID: number;
  MOBILE_NO: string;
  ORDER_ID: number;
  PAYMENT_STATUS: string;
  READ_ONLY: string;
  SALUTATION: string;
  SERVICE_ID: number;
  TAX_AMOUNT: string;
  TAX_RATE: string | null;
  TOTAL_AMOUNT: string;
}

interface InvoiceInterface {
  ARCHIVE_FLAG: string;
  BILLING_ADDRESS_ID: number;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  CUSTOMER_NAME: string;
  CUSTOMER_TYPE: string;
  DISCOUNT_AMOUNT: string;
  EMAIL: string;
  FINAL_AMOUNT: string;
  ID: number;
  INVOICE_DATE: string;
  INVOICE_URL: string;
  JOB_CARD_ID: number;
  MOBILE_NO: string;
  ORDER_ID: number;
  PAYMENT_STATUS: string;
  READ_ONLY: string;
  SALUTATION: string;
  SERVICE_ID: number;
  TAX_AMOUNT: string;
  TAX_RATE: string | null;
  TOTAL_AMOUNT: string;
}

type cartGetType = {
  TYPE: string;
  CART_DETAILS: cartInterface[];
  CART_INFO: cartSummeryInterface[];
};

type ticketInterface = {
  title: any;
  description: any;
  ANSWER_AGENT: null;
  ARCHIVE_FLAG: 'F';
  CLIENT_ID: 1;
  CLOUD_ID: string;
  CREATED_MODIFIED_DATE: string;
  CREATER_ID: number | null;
  CREATER_NAME: string | null;
  CREATOR_EMPLOYEE_ID: number | null;
  CREATOR_EMPLOYEE_NAME: string | null;
  DATE: string;
  DEPARTMENT_ID: number;
  DEPARTMENT_NAME: string | null;
  EMAIL_ID: string;
  FIRST_RESOLVED_TIME: string | null;
  ID: number;
  IS_LAST: number;
  IS_TAKEN: number;
  IS_TAKEN_STATUS: string;
  IS_TAKEN_USER_NAME: string | null;
  LAST_RESPONDED: string;
  MOBILE_NO: string;
  ON_HOLD: string | null;
  ORGANISATION_NAME: string;
  ORG_ID: number;
  PRIORITY: string;
  QUESTION: string;
  READ_ONLY: string;
  RECIVER_AGENT: string | null;
  RECIVER_ID: string | null;
  RECIVER_NAME: string | null;
  STATUS: string;
  SUBJECT: string;
  SUPPORT_AGENT_NAME: string | null;
  TAKEN_BY_USER_ID: number;
  TICKET_GROUP_ID: number;
  TICKET_GROUP_PARENT_VALUE: string;
  TICKET_GROUP_TYPE: string;
  TICKET_GROUP_VALUE: string;
  TICKET_NO: string;
  TICKET_TAKEN_DEPARTMENT: string | null;
  TICKET_TAKEN_DEPARTMENT_ID: string | null;
  TICKET_TAKEN_DEPARTMENT_NAME: string | null;
  TICKET_TAKEN_EMPLOYEE: string | null;
  USER_ID: number;
  USER_TYPE: string;
};

interface ticketDetailsInterface {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CREATER_NAME: string;
  DATE: string;
  DEPARTMENT_ID: number;
  DEPARTMENT_NAME: string | null;
  DESCRIPTION: string;
  EMAIL_ID: string;
  ID: number;
  IS_TAKEN: number;
  IS_TAKEN_STATUS: string;
  LAST_RESPONDED: string;
  MOBILE_NO: string;
  PRIORITY: string;
  QUESTION: string;
  READ_ONLY: string;
  RECIVER_NAME: string | null;
  SENDER: string; // SENDER == 'X' Center;SENDER == 'S' Self; SENDER == 'U' Other
  SENDER_ID: number;

  STATUS: string;
  TAKEN_BY_USER_ID: number;
  TICKET_GROUP_ID: number;
  TICKET_MASTER_ID: number;
  TICKET_NO: string;
  TICKET_TAKEN_DEPARTMENT: string | null;
  TICKET_TAKEN_EMPLOYEE: string | null;
  URL: string | null;
  USER_ID: number;
}
